name: IntegrationTest
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - { user: SciML, repo: ModelingToolkit.jl, group: All }
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      julia-version: "1"
      repo: "${{ matrix.package.repo }}"
      owner: "${{ matrix.package.user }}"
      group: "${{ matrix.package.group }}"
    secrets: "inherit"
